---
title: "wk2-workshop"
author: "Shae-Anne"
date: "2024-01-24"
output:
  github_document:
    toc: true
    toc_depth: 2
    fig_width: 7
    fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read in data
```{r}
df = readRDS("data/wk2_stocks.rds")
head(df)
```

## Statistics 
+ The cumulative returns of the S&P index during this period is `r round(sum(df$SPY_returns)*100,2)`%.
+ The average daily returns of the S&P index during this period is `r round(mean(df$SPY_returns)*100,2)`%.
+ The standard deviation of the daily returns of the S&P index during this period is `r round(sd(df$SPY_returns)*100,2)`%.

## Plot: S&P Prices
```{r message = FALSE}
library(tidyverse)
ggplot(data = df, aes(x = date, y = SPY_prices)) +
  geom_line()
```

## Plot: S&P Yearly Returns
```{r}
df %>% 
  mutate(year = year(date)) %>%
  filter(year <= 2023) %>%
  group_by(year) %>%
  summarize(yr_returns = sum(SPY_returns)*100) %>%
  ggplot(aes(x = year, y = yr_returns)) + 
  geom_col()
```
